name: Hello World Workflow

jobs:
  say_hello:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Print Hello World
        run: echo "Hello World"
